# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Test-4-4' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Test-4-4
pod "PGFramework"
  target 'Test-4-4Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Test-4-4UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
